### ISSUE TITLE
匿名回答保存出错

### ISSUE THREAD

**Issue by gikillu** [qtqz/zhihu-backup-collect#1]
您好，您的这个脚本非常实用，但是匿名回答好像无法保存，您可以看下是什么问题吗

![屏幕截图 2024-03-20 102615](https://github.com/qtqz/zhihu-backup-collect/assets/106650106/aa687dc3-7b27-4d86-bd2d-100444d12531)

**Comment by qtqz** [comment]
0.8.8 已修复

**Comment by gikillu** [comment]
赞，剪切的功能真的好用
