### ISSUE TITLE
24.11.13（0.9.22）更新后脚本无法使用

### ISSUE THREAD

**Issue by Xiaoxiao202306** [qtqz/zhihu-backup-collect#7]
24.11.13之前均能正常使用脚本，更新后脚本在edge和Chrome浏览器均无法使用

**Comment by Xiaoxiao202306** [comment]
感觉可能和版本无关（因为我换了更低级的版本也无法正常使用），个人猜想是不是知乎网页版改版了呢？

**Comment by Xiaoxiao202306** [comment]
解决了！我在“扩展”里打开了开发者模式，就可以正常使用了。另外作者有考虑开个赞赏码吗，这个插件对我帮助很大。

**Comment by qtqz** [comment]
好，赞赏码在咱 github 主页有哦
