### ISSUE TITLE
improve: 复制的时候也增加frontmatter

### ISSUE THREAD

**Issue by indexss** [qtqz/zhihu-backup-collect#8]
你好作者，感谢您的插件。在使用的过程中，我发现在zip下载得到的md文件中是有frontmatter的，但复制到的没有。
我认为通过复制的方式把文章放到自己知识库的需求应该是有的，所以作者是否可以增加一个选项，选择复制时是否添加frontmatter? 感谢！
另外，感谢这个插件，一键就能收集自己喜欢的文章了，效率大提升 :)

**Comment by qtqz** [comment]
已添加，需在菜单手动开启
